apiVersion: v1
kind: Namespace
metadata:
  name: prod

apiVersion: v1
kind: Namespace
metadata:
  name: client

apiVersion: v1
kind: Namespace
metadata:
  name: dev


apiVersion: v1
kind: Namespace
metadata:
  name: system
