apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: prod
  labels:
    app: hello-world-web-app-development
    env: development
spec:
  template:
    metadata:
      labels:
        app: hello-world-web-app-develop
  containers:
    - name: hello-world
      image: dockercloud/hello-world
      volumeMounts:
      - mountPath: /var/run/secrets/tokens
        name: adminToken
  serviceAccountName: admin
  volumes:
  - name: adminToken
    projected:
      sources:
      - serviceAccountToken:
          path: adminToken
          expirationSeconds: 86400
          audience: some-oidc-audience
      ports:
        - containerPort: 80
