apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-web-app-develo
  labels:
    app: hello-world-web-app-development
    env: development
spec:
  selector:
    matchLabels:
      app: hello-world-web-app-development
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-web-app-develop
    spec:
      containers:
        - name: hello-world-web-app-develop
          image: dockercloud/hello-world
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
