kind: Service
apiVersion: v1
metadata:
  name: network_deployment_web_http
spec:
  #type: NodePort
  selector:
    app: service_web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 32000
  type: LoadBalancer
