apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: applicationingress
spec:
  rules:
    - host: quentin.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: network_deployment_web_http
                port:
                  number: 80
