kind: Service
apiVersion: v1
metadata:
  name: devops303-service
spec:
  type: NodePort
  selector:
    app: devops303-web-app-development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
