kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: client
subjects:
- kind: ServiceAccount
  name: client
roleRef:
  kind: Role
  name: pod-read-only
  apiGroup: rbac.authorization.k8s.io