version: "3.9"
services:
  redi:
    image: redis:5-alpine
  apps:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules

    deploy:
      replicas: 3
    # ports:
    #   - "8889:8884"
    environment:
      - REDIS_HOST=redi
      - REDIS_PORT=6379
    command: ["nodemon", "-L", "app.js"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf :/etc/nginx/nginx.conf
    ports:
      - "88:80"
