kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
spec:
  #type: NodePort
  selector:
    app: hello-world-web-app-development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 32000
